apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-ci-cd-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balaji014/ml-ci-cd-demo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true